# Generated by Django 3.0.5 on 2020-04-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='Bairro',
            new_name='bairro',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='tipodeanimal',
        ),
        migrations.AddField(
            model_name='pet',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Gato', 'Gato'), ('Cachorro', 'Cachorro'), ('Outro', 'Outro')], max_length=30, null=True),
        ),
    ]
