# Generated by Django 3.0.5 on 2020-04-28 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_auto_20200428_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='photo',
            new_name='foto',
        ),
    ]
